defmodule Voria2.Repo.Migrations.AddBlogPages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:blog_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :citext, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:blog_categories, [:name], name: "blog_categories_unique_name_index")

    create table(:blog_articles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :body, :text, null: false
      add :cover_image_url, :text
      add :published, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:blog_articles, [:slug], name: "blog_articles_unique_slug_index")

    create table(:blog_article_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :article_id,
          references(:blog_articles,
            column: :id,
            name: "blog_article_categories_article_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :category_id,
          references(:blog_categories,
            column: :id,
            name: "blog_article_categories_category_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:blog_article_categories, [:article_id, :category_id],
             name: "blog_article_categories_unique_article_category_index"
           )
  end

  def down do
    drop_if_exists unique_index(:blog_article_categories, [:article_id, :category_id],
                     name: "blog_article_categories_unique_article_category_index"
                   )

    drop constraint(:blog_article_categories, "blog_article_categories_article_id_fkey")

    drop constraint(:blog_article_categories, "blog_article_categories_category_id_fkey")

    drop table(:blog_article_categories)

    drop_if_exists unique_index(:blog_articles, [:slug], name: "blog_articles_unique_slug_index")

    drop table(:blog_articles)

    drop_if_exists unique_index(:blog_categories, [:name],
                     name: "blog_categories_unique_name_index"
                   )

    drop table(:blog_categories)
  end
end
