defmodule Voria2.Repo.Migrations.AddWebcamShotRangeIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:webcam_shots, [:webcam_id, :captured_at])
  end

  def down do
    drop_if_exists index(:webcam_shots, [:webcam_id, :captured_at])
  end
end
