defmodule Voria2.Repo.Migrations.AddCascadeDeletes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and then hand-edited to use raw SQL for TimescaleDB hypertables, which
  do not support ALTER COLUMN (due to dependent views on chunk columns).
  """

  use Ecto.Migration

  # Hypertable measurement tables — must use raw DDL (no ALTER COLUMN).
  @hypertable_fk_changes [
    {"wind_measurements", "sensor_installation_id",
     "wind_measurements_sensor_installation_id_fkey", "sensor_installations"},
    {"temperature_measurements", "sensor_installation_id",
     "temperature_measurements_sensor_installation_id_fkey", "sensor_installations"},
    {"rain_measurements", "sensor_installation_id",
     "rain_measurements_sensor_installation_id_fkey", "sensor_installations"},
    {"pressure_measurements", "sensor_installation_id",
     "pressure_measurements_sensor_installation_id_fkey", "sensor_installations"},
    {"humidity_measurements", "sensor_installation_id",
     "humidity_measurements_sensor_installation_id_fkey", "sensor_installations"},
    {"custom_measurements", "sensor_installation_id",
     "custom_measurements_sensor_installation_id_fkey", "sensor_installations"}
  ]

  def up do
    # Non-hypertable tables: safe to use Ecto modify.
    drop constraint(:station_api_keys, "station_api_keys_station_id_fkey")

    alter table(:station_api_keys) do
      modify :station_id,
             references(:stations,
               column: :id,
               name: "station_api_keys_station_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:sensor_installations, "sensor_installations_station_id_fkey")

    alter table(:sensor_installations) do
      modify :station_id,
             references(:stations,
               column: :id,
               name: "sensor_installations_station_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:rain_cumulative_states, "rain_cumulative_states_sensor_installation_id_fkey")

    alter table(:rain_cumulative_states) do
      modify :sensor_installation_id,
             references(:sensor_installations,
               column: :id,
               name: "rain_cumulative_states_sensor_installation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    # Hypertable tables: drop old FK and add new one with ON DELETE CASCADE.
    for {table, col, constraint_name, ref_table} <- @hypertable_fk_changes do
      execute("""
      ALTER TABLE #{table}
        DROP CONSTRAINT IF EXISTS #{constraint_name};
      """)

      execute("""
      ALTER TABLE #{table}
        ADD CONSTRAINT #{constraint_name}
        FOREIGN KEY (#{col}) REFERENCES #{ref_table}(id) ON DELETE CASCADE;
      """)
    end
  end

  def down do
    drop constraint(:rain_cumulative_states, "rain_cumulative_states_sensor_installation_id_fkey")

    alter table(:rain_cumulative_states) do
      modify :sensor_installation_id,
             references(:sensor_installations,
               column: :id,
               name: "rain_cumulative_states_sensor_installation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:sensor_installations, "sensor_installations_station_id_fkey")

    alter table(:sensor_installations) do
      modify :station_id,
             references(:stations,
               column: :id,
               name: "sensor_installations_station_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:station_api_keys, "station_api_keys_station_id_fkey")

    alter table(:station_api_keys) do
      modify :station_id,
             references(:stations,
               column: :id,
               name: "station_api_keys_station_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    for {table, col, constraint_name, ref_table} <- @hypertable_fk_changes do
      execute("""
      ALTER TABLE #{table}
        DROP CONSTRAINT IF EXISTS #{constraint_name};
      """)

      execute("""
      ALTER TABLE #{table}
        ADD CONSTRAINT #{constraint_name}
        FOREIGN KEY (#{col}) REFERENCES #{ref_table}(id);
      """)
    end
  end
end
