defmodule Voria2.Repo.Migrations.AddMeasurementIdempotency do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    deduplicate_measurements("wind_measurements")
    deduplicate_measurements("temperature_measurements")
    deduplicate_measurements("rain_measurements")
    deduplicate_measurements("pressure_measurements")
    deduplicate_measurements("humidity_measurements")
    deduplicate_measurements("custom_measurements")

    create unique_index(:wind_measurements, [:sensor_installation_id, :measured_at],
             name: "wind_measurements_unique_sensor_timestamp_index"
           )

    create unique_index(:temperature_measurements, [:sensor_installation_id, :measured_at],
             name: "temperature_measurements_unique_sensor_timestamp_index"
           )

    create unique_index(:rain_measurements, [:sensor_installation_id, :measured_at],
             name: "rain_measurements_unique_sensor_timestamp_index"
           )

    create unique_index(:pressure_measurements, [:sensor_installation_id, :measured_at],
             name: "pressure_measurements_unique_sensor_timestamp_index"
           )

    create unique_index(:humidity_measurements, [:sensor_installation_id, :measured_at],
             name: "humidity_measurements_unique_sensor_timestamp_index"
           )

    create unique_index(:custom_measurements, [:sensor_installation_id, :measured_at],
             name: "custom_measurements_unique_sensor_timestamp_index"
           )
  end

  def down do
    drop_if_exists unique_index(:custom_measurements, [:sensor_installation_id, :measured_at],
                     name: "custom_measurements_unique_sensor_timestamp_index"
                   )

    drop_if_exists unique_index(:humidity_measurements, [:sensor_installation_id, :measured_at],
                     name: "humidity_measurements_unique_sensor_timestamp_index"
                   )

    drop_if_exists unique_index(:pressure_measurements, [:sensor_installation_id, :measured_at],
                     name: "pressure_measurements_unique_sensor_timestamp_index"
                   )

    drop_if_exists unique_index(:rain_measurements, [:sensor_installation_id, :measured_at],
                     name: "rain_measurements_unique_sensor_timestamp_index"
                   )

    drop_if_exists unique_index(
                     :temperature_measurements,
                     [:sensor_installation_id, :measured_at],
                     name: "temperature_measurements_unique_sensor_timestamp_index"
                   )

    drop_if_exists unique_index(:wind_measurements, [:sensor_installation_id, :measured_at],
                     name: "wind_measurements_unique_sensor_timestamp_index"
                   )
  end

  defp deduplicate_measurements(table) do
    execute """
    WITH duplicates AS (
      SELECT ctid
      FROM (
        SELECT
          ctid,
          row_number() OVER (
            PARTITION BY sensor_installation_id, measured_at
            ORDER BY xmin DESC, ctid DESC
          ) AS row_num
        FROM #{table}
      ) ranked
      WHERE row_num > 1
    )
    DELETE FROM #{table}
    WHERE ctid IN (SELECT ctid FROM duplicates)
    """
  end
end
