defmodule Voria2.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:wind_measurements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :measured_at, :utc_datetime_usec, null: false
      add :u, :float, null: false
      add :v, :float, null: false
      add :gust, :float
      add :sensor_installation_id, :uuid, null: false
    end

    create table(:webcams, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :stream_url, :text
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :installation_id, :uuid, null: false
    end

    create table(:webcam_shots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :captured_at, :utc_datetime_usec, null: false
      add :s3_key, :text, null: false
      add :s3_bucket, :text, null: false
      add :original_hash, :text, null: false
      add :width, :bigint
      add :height, :bigint
      add :file_size_bytes, :bigint
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :webcam_id,
          references(:webcams,
            column: :id,
            name: "webcam_shots_webcam_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:webcam_shots, [:original_hash], unique: true)

    create table(:webcam_api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :label, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :webcam_id,
          references(:webcams,
            column: :id,
            name: "webcam_api_keys_webcam_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:webcam_api_keys, [:key], name: "webcam_api_keys_unique_key_index")

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :name, :text, null: false
      add :admin, :boolean, null: false, default: false
      add :hashed_password, :text, null: false
      add :confirmed_at, :utc_datetime_usec
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:temperature_measurements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :measured_at, :utc_datetime_usec, null: false
      add :value, :float, null: false
      add :sensor_installation_id, :uuid, null: false
    end

    create table(:stations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :installation_id, :uuid, null: false
    end

    create table(:station_api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :label, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :station_id,
          references(:stations,
            column: :id,
            name: "station_api_keys_station_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:station_api_keys, [:key], name: "station_api_keys_unique_key_index")

    create table(:sensor_installations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:wind_measurements) do
      modify :sensor_installation_id,
             references(:sensor_installations,
               column: :id,
               name: "wind_measurements_sensor_installation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:temperature_measurements) do
      modify :sensor_installation_id,
             references(:sensor_installations,
               column: :id,
               name: "temperature_measurements_sensor_installation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:sensor_installations) do
      add :installed_at, :date, null: false
      add :removed_at, :date
      add :model, :text
      add :notes, :text
      add :rain_mode, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :station_id,
          references(:stations,
            column: :id,
            name: "sensor_installations_station_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :measurement_type_id, :uuid, null: false
    end

    create table(:rain_measurements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :measured_at, :utc_datetime_usec, null: false
      add :interval_mm, :float, null: false, default: 0.0

      add :sensor_installation_id,
          references(:sensor_installations,
            column: :id,
            name: "rain_measurements_sensor_installation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:rain_cumulative_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :last_cumulative_value, :float, null: false
      add :last_updated_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sensor_installation_id,
          references(:sensor_installations,
            column: :id,
            name: "rain_cumulative_states_sensor_installation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:rain_cumulative_states, [:sensor_installation_id],
             name: "rain_cumulative_states_unique_sensor_index"
           )

    create table(:pressure_measurements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :measured_at, :utc_datetime_usec, null: false
      add :value, :float, null: false

      add :sensor_installation_id,
          references(:sensor_installations,
            column: :id,
            name: "pressure_measurements_sensor_installation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:measurement_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sensor_installations) do
      modify :measurement_type_id,
             references(:measurement_types,
               column: :id,
               name: "sensor_installations_measurement_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:measurement_types) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :unit, :text
      add :storage_type, :text, null: false
      add :description, :text
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "measurement_types_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:measurement_types, [:slug], name: "measurement_types_unique_slug_index")

    create table(:installations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:webcams) do
      modify :installation_id,
             references(:installations,
               column: :id,
               name: "webcams_installation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:webcams, [:slug], name: "webcams_unique_slug_index")

    alter table(:stations) do
      modify :installation_id,
             references(:installations,
               column: :id,
               name: "stations_installation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:stations, [:slug], name: "stations_unique_slug_index")

    alter table(:installations) do
      add :name, :text, null: false
      add :description, :text
      add :latitude, :float, null: false
      add :longitude, :float, null: false
      add :altitude, :float
      add :timezone, :text
      add :country, :text
      add :city, :text
      add :picture_keys, {:array, :text}, default: []
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "installations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:installations, [:user_id, :name],
             name: "installations_unique_name_per_user_index"
           )

    create table(:humidity_measurements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :measured_at, :utc_datetime_usec, null: false
      add :value, :float, null: false

      add :sensor_installation_id,
          references(:sensor_installations,
            column: :id,
            name: "humidity_measurements_sensor_installation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:faults, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :fault_type, :text, null: false
      add :reason, :text, null: false
      add :detected_at, :utc_datetime_usec, null: false
      add :resolved_at, :utc_datetime_usec
      add :resolved_by_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :station_id,
          references(:stations,
            column: :id,
            name: "faults_station_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :webcam_id,
          references(:webcams,
            column: :id,
            name: "faults_webcam_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :sensor_installation_id,
          references(:sensor_installations,
            column: :id,
            name: "faults_sensor_installation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:faults, [:sensor_installation_id, :resolved_at],
             name: "faults_sensor_installation_id_resolved_at_idx",
             where: "sensor_installation_id IS NOT NULL"
           )

    create index(:faults, [:webcam_id, :resolved_at],
             name: "faults_webcam_id_resolved_at_idx",
             where: "webcam_id IS NOT NULL"
           )

    create index(:faults, [:station_id, :resolved_at],
             name: "faults_station_id_resolved_at_idx",
             where: "station_id IS NOT NULL"
           )

    execute """
    ALTER TABLE faults ADD CONSTRAINT faults_exactly_one_subject
    CHECK (
      (CASE WHEN station_id IS NOT NULL THEN 1 ELSE 0 END +
       CASE WHEN webcam_id IS NOT NULL THEN 1 ELSE 0 END +
       CASE WHEN sensor_installation_id IS NOT NULL THEN 1 ELSE 0 END) = 1
    )
    """

    create table(:custom_measurements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :measured_at, :utc_datetime_usec, null: false
      add :value, :float
      add :raw, :map

      add :sensor_installation_id,
          references(:sensor_installations,
            column: :id,
            name: "custom_measurements_sensor_installation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :measurement_type_id,
          references(:measurement_types,
            column: :id,
            name: "custom_measurements_measurement_type_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:custom_measurements, "custom_measurements_sensor_installation_id_fkey")

    drop constraint(:custom_measurements, "custom_measurements_measurement_type_id_fkey")

    drop table(:custom_measurements)

    drop constraint(:faults, "faults_station_id_fkey")

    drop constraint(:faults, "faults_webcam_id_fkey")

    drop constraint(:faults, "faults_sensor_installation_id_fkey")

    drop_if_exists index(:faults, [:station_id, :resolved_at],
                     name: "faults_station_id_resolved_at_idx"
                   )

    drop_if_exists index(:faults, [:webcam_id, :resolved_at],
                     name: "faults_webcam_id_resolved_at_idx"
                   )

    drop_if_exists index(:faults, [:sensor_installation_id, :resolved_at],
                     name: "faults_sensor_installation_id_resolved_at_idx"
                   )

    drop table(:faults)

    drop constraint(:humidity_measurements, "humidity_measurements_sensor_installation_id_fkey")

    drop table(:humidity_measurements)

    drop_if_exists unique_index(:installations, [:user_id, :name],
                     name: "installations_unique_name_per_user_index"
                   )

    drop constraint(:installations, "installations_user_id_fkey")

    alter table(:installations) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :is_active
      remove :picture_keys
      remove :city
      remove :country
      remove :timezone
      remove :altitude
      remove :longitude
      remove :latitude
      remove :description
      remove :name
    end

    drop_if_exists unique_index(:stations, [:slug], name: "stations_unique_slug_index")

    drop constraint(:stations, "stations_installation_id_fkey")

    alter table(:stations) do
      modify :installation_id, :uuid
    end

    drop_if_exists unique_index(:webcams, [:slug], name: "webcams_unique_slug_index")

    drop constraint(:webcams, "webcams_installation_id_fkey")

    alter table(:webcams) do
      modify :installation_id, :uuid
    end

    drop table(:installations)

    drop_if_exists unique_index(:measurement_types, [:slug],
                     name: "measurement_types_unique_slug_index"
                   )

    drop constraint(:measurement_types, "measurement_types_user_id_fkey")

    alter table(:measurement_types) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :is_active
      remove :description
      remove :storage_type
      remove :unit
      remove :slug
      remove :name
    end

    drop constraint(:sensor_installations, "sensor_installations_measurement_type_id_fkey")

    alter table(:sensor_installations) do
      modify :measurement_type_id, :uuid
    end

    drop table(:measurement_types)

    drop constraint(:pressure_measurements, "pressure_measurements_sensor_installation_id_fkey")

    drop table(:pressure_measurements)

    drop_if_exists unique_index(:rain_cumulative_states, [:sensor_installation_id],
                     name: "rain_cumulative_states_unique_sensor_index"
                   )

    drop constraint(:rain_cumulative_states, "rain_cumulative_states_sensor_installation_id_fkey")

    drop table(:rain_cumulative_states)

    drop constraint(:rain_measurements, "rain_measurements_sensor_installation_id_fkey")

    drop table(:rain_measurements)

    drop constraint(:sensor_installations, "sensor_installations_station_id_fkey")

    alter table(:sensor_installations) do
      remove :measurement_type_id
      remove :station_id
      remove :updated_at
      remove :inserted_at
      remove :rain_mode
      remove :notes
      remove :model
      remove :removed_at
      remove :installed_at
    end

    drop constraint(
           :temperature_measurements,
           "temperature_measurements_sensor_installation_id_fkey"
         )

    alter table(:temperature_measurements) do
      modify :sensor_installation_id, :uuid
    end

    drop constraint(:wind_measurements, "wind_measurements_sensor_installation_id_fkey")

    alter table(:wind_measurements) do
      modify :sensor_installation_id, :uuid
    end

    drop table(:sensor_installations)

    drop_if_exists unique_index(:station_api_keys, [:key],
                     name: "station_api_keys_unique_key_index"
                   )

    drop constraint(:station_api_keys, "station_api_keys_station_id_fkey")

    drop table(:station_api_keys)

    drop table(:stations)

    drop table(:temperature_measurements)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)

    drop_if_exists unique_index(:webcam_api_keys, [:key],
                     name: "webcam_api_keys_unique_key_index"
                   )

    drop constraint(:webcam_api_keys, "webcam_api_keys_webcam_id_fkey")

    drop table(:webcam_api_keys)

    drop constraint(:webcam_shots, "webcam_shots_webcam_id_fkey")

    drop_if_exists index(:webcam_shots, [:original_hash])

    drop table(:webcam_shots)

    drop table(:webcams)

    drop table(:wind_measurements)
  end
end
